### ISSUE TITLE
Create Snap and Flatpak for Terminator

### ISSUE THREAD

**Issue by mattrose** [gnome-terminator/terminator#206]
So, there's two reasons for this:

1.  There's a lot of demand for it.
2.  There's a lot of functionality that would be nice to have in terminator, but is unavailable through the stock VTE library.  There are patches that exist, but we cannot rely on them being there.

**Comment by mattrose** [comment]
If anyone has any experience creating these, PRs would be greatly appreciated.

**Comment by dafanasiev** [comment]
I try to make snap... 

But i have no idea how to deal with d-bus, because this code:
```python
BUS_BASE = 'net.tenshu.Terminator2'
BUS_PATH = '/net/tenshu/Terminator2'
try:
    # Try and include the X11 display name in the dbus bus name
    DISPLAY = Gdk.get_display().partition('.')[0]
    # In Python 3, hash() uses a different seed on each run, so use hashlib
    DISPLAY = hashlib.md5(DISPLAY.encode('utf-8')).hexdigest()
    BUS_NAME = '%s%s' % (BUS_BASE, DISPLAY)
except:
    BUS_NAME = BUS_BASE
```
`snapcraft.yaml` require constant name for bus name. Bad app design?

file: `snapcraft.yaml`:
```yaml
name: terminator
version: "1.92"
summary: Terminator is an open-source terminal emulator.
description: |
  Multiple terminals in one window.
  The goal of this project is to produce a useful tool for arranging terminals.
  It is inspired by programs such as gnome-multi-term, quadkonsole,
  etc. in that the main focus is arranging terminals in grids
  (tabs is the most common default method, which Terminator also supports).

#icon: https://raw.githubusercontent.com/gnome-terminator/terminator/master/data/icons/hicolor/scalable/apps/terminator.svg
grade: stable # Use stable or devel
confinement: classic
license: ISC
base: core20

architectures:
  #- build-on: [amd64, armhf]   # Need fix for multipass.
  - build-on: [amd64]
    run-on: [amd64]

apps:
  terminator:
    command: bin/terminator
    desktop: share/applications/terminator.desktop
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.8/site-packages

parts:
  terminator:
    plugin: python
    source: https://github.com/gnome-terminator/terminator/releases/download/v1.92/terminator-1.92.tar.gz

    build-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-psutil
      - python3-configobj
      - gir1.2-keybinder-3.0
      - gir1.2-vte-2.91
      - gettext
      - intltool
      - dbus-x11
      - libgirepository1.0-dev
      - libcairo2-dev
      - python3-wheel
      - libdbus-glib-1-dev
    stage-packages:
      - python3-gi
      - python3-gi-cairo
      - python3-psutil
      - python3-configobj
      - gir1.2-keybinder-3.0
      - gir1.2-vte-2.91
      - gettext
      - intltool
      - dbus-x11
      - libcairo2
      - libgirepository-1.0-1
```

To use this file:
```sh
snapcraft
snap install terminator_1.92_amd64.snap --classic --dangerous
```
